version: '3.3'
services:
  httpserver:
    build: .
    container_name: httpserver
    restart: "no"
    ports:
      - 8000:80
    volumes:
      - ..:/var/www/html

#  httpserver-composer:
#    image: composer
#    container_name: httpserver-composer
#    restart: "no"
#    user: 1000:1000

networks:
  default:
    external:
      name: dev-net
